#!/bin/sh
echo "Flushing redo cache..." >&2

if test -z $TMPDIR
then
  TMPDIR=/tmp
fi

rm -rf $TMPDIR/redo-$USER/*/cache/*
rm -rf $TMPDIR/redo-$USER/*/db_locks/*
rm -rf $TMPDIR/redo-$USER/*/target_locks/*
