name: redo
services:
    redo:
        image: ghcr.io/dinkelk/redo:latest
        build:
            context: ..
            dockerfile: docker/Dockerfile
            platforms:
                - linux/amd64
                - linux/arm64
        container_name: redo_container
        command: sleep infinity
