name: redo
services:
    redo:
        image: ghcr.io/dinkelk/redo:latest
        build:
            context: ..
            dockerfile: docker/Dockerfile
            x-bake:
                platforms:
                    - linux/amd64
                    - linux/arm64
        container_name: redo_container
        volumes:
            - type: bind
              source: ../../redo
              target: /workspace/redo
        command: sleep infinity
